use sysadmin;
use warehouse compute_wh;
use database igg_source_dev;
use schema bloomberg_bond;


CREATE OR REPLACE TABLE bloomberg_index (
    Key INT,
    PrcDate DATE,
    FullName STRING,
    idIndex INT,
    NumIssuesB FLOAT,
    NumIssuesF FLOAT,
    Currency STRING,
    RetType INT,
    Coupon FLOAT,
    Maturity FLOAT,
    Quality STRING,
    Price FLOAT,
    MarketValue FLOAT,
    YieldWorst FLOAT,
    YieldMaturity FLOAT,
    DurationModF FLOAT,
    DurationModWorst FLOAT,
    DurationWorstF FLOAT,
    Convexity FLOAT,
    OAS FLOAT,
    DurationModB FLOAT,
    RetDaily FLOAT,
    RetMTD FLOAT,
    Ret3M FLOAT,
    Ret6M FLOAT,
    Ret12M FLOAT,
    RetYTD FLOAT,
    RetMTDPrice FLOAT,
    RetMTDCoupon FLOAT,
    RetMTDPaydown FLOAT,
    RetMTDCurrency FLOAT,
    ExcessRet FLOAT,
    RetInception FLOAT,
    IndexValue FLOAT,
    BBGTicker STRING,
    OASD FLOAT,
    OutstandingE FLOAT,
    FileName VARCHAR(255),
    FolderName VARCHAR(255),
    AWS_Timestamp TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE bloomberg_bonds (
  Key INT,
  Cusip STRING,
  ISIN STRING,
  Issuer STRING,
  Ticker STRING,
  Coupon FLOAT,
  MaturDate STRING,
  QualityB STRING,
  QualityE STRING,
  Currency STRING,
  IssrClsL1 STRING,
  IssrClsL2 STRING,
  IssrClsL3 STRING,
  IssrClsL4 STRING,
Country STRING,
OutstandB FLOAT,
OutstandE FLOAT,
PriceB FLOAT,
PriceE FLOAT,
AccrIntB FLOAT,
AccrIntE FLOAT,
MrkValBeg FLOAT,
MrktValue FLOAT,
YldWorstE FLOAT,
YldMatE FLOAT,
Maturity FLOAT,
AvgLife FLOAT,
ISMA_MDur FLOAT,
DurAdjMod FLOAT,
DurMatMod FLOAT,
DurWrsMod FLOAT,
OasSprDur FLOAT,
ConvAdj FLOAT,
OAS_bp FLOAT,
RetTotal FLOAT,
RetPrice FLOAT,
RetCoupon FLOAT,
RetPayDwn FLOAT,
RetCurncy FLOAT,
RUCash FLOAT,
RUDurAdjM FLOAT,
RUMVCash FLOAT,
RUMVSecry FLOAT,
RUMVTotal FLOAT,
RUMVTotLc FLOAT,
RUOutsBas FLOAT,
RUOutsLoc FLOAT,
OutstE_$USD FLOAT,
CallFlag STRING,
CapSecTyp STRING,
ExtendFlg STRING,
FloatCpnF STRING,
IssrClass STRING,
IssrClsCd STRING,
LB_Class STRING,
LB_ClsDND STRING,
LB_level2 STRING,
PutFlag STRING,
SchdPaymF STRING,
Sector STRING,
SinkType STRING,
TradToFlg STRING,
TypCollat STRING,
TypGuarnt STRING,
TypPlacmt STRING,
TypSubord STRING,
Figi STRING,
ProductCurrency STRING,
OAStoWrsE FLOAT,
MrktValueUSD FLOAT,
MrkValBegUSD FLOAT,
MVLocB FLOAT,
MVLocE FLOAT,
RetTotalUSD FLOAT,
RUMVSecryUSD FLOAT,
RUMVTotalUSD FLOAT,
MVHedgeB FLOAT,
MVHedgeE FLOAT,
MaturityE FLOAT,
FileName VARCHAR(255),
FolderName VARCHAR(255),
AWS_Timestamp TIMESTAMP_LTZ
);

CREATE or replace TABLE bloomberg_map (
    Key INT,
    idIndex INT,
    Cusip VARCHAR(255),
    MrktValue FLOAT,
    OutstandE FLOAT,
    Figi VARCHAR(255),
    ProductCurrency VARCHAR(3),
    Percent FLOAT,
    FileName VARCHAR(255),
    FolderName VARCHAR(255),
    AWS_Timestamp TIMESTAMP_LTZ
);

