CREATE OR REPLACE TABLE FUND_HOLDINGS (

Key INT,
ASOF_DATE DATE,
ISIN STRING,
CUSIP STRING,
POSITION_AMOUNT BIGINT,
CURRENCY VARCHAR(3),
FUND_ID STRING,
File_Name VARCHAR(255),
Folder_Name VARCHAR(255),
AWS_Timestamp TIMESTAMP_LTZ

);